# Generated by Django 2.0.1 on 2018-01-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finish_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(related_name='todos', to='apiv1.Tag'),
        ),
        migrations.AlterField(
            model_name='percenttodo',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
